version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/init.sql
    command: --init-file /init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: records
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306


volumes:
  db_data: {}